project:
  type: website
  output-dir: docs

website:
  title: "Final_Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - EDA.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    toc-float: true
    favicon: /Users/bevanwatson/Desktop/SPRING2024/MATH378/Final_Project/images/penguin_favicon.jpeg

editor: visual

